// Generated by lab/scripts/generate-aot-hook-binding.mjs; fallback map is reviewed there.
#include "AotModeConfig.h"
#if HYBRIDCLR_ENABLE_AOT_SELECTION
#include "metadata/MetadataModule.h"
#include "metadata/AOTHomologousImage.h"
#include "DheRuntime.h"
#include <atomic>
using namespace hybridclr::metadata;
namespace hybridclr { namespace startup {
static Image* LegacyInterpreterImage(const MethodInfo* methodInfo) {
    return IsInterpreterMethod(methodInfo) ? MetadataModule::GetImage(methodInfo->klass)
        : static_cast<Image*>(AOTHomologousImage::FindImageByAssembly(
            methodInfo->klass->rank ? il2cpp_defaults.corlib->assembly : methodInfo->klass->image->assembly));
}
static const PropertyInfo* LegacyProperty(Il2CppClass* klass, uint32_t index) {
    if (index >= klass->property_count) return nullptr;
#if UNITY_ENGINE_TUANJIE
    return klass->properties[index];
#else
    return &klass->properties[index];
#endif
}
struct HookTable {
    int mode;
    bool (*Metadata_TryCopyDheBoxedValueToCurrent_0)(Il2CppObject* value, Il2CppClass* currentClass, void* destination);
    Image* (*Metadata_GetUnderlyingInterpreterImage_0)(const MethodInfo* methodInfo);
    Image* (*Metadata_GetInterpreterResolveImage_0)(const MethodInfo* methodInfo);
    bool (*Metadata_HasDheReflectedParent_0)(Il2CppClass* reflectedClass, Il2CppClass* declaringClass);
    bool (*Metadata_IsDheEquivalentClass_0)(Il2CppClass* left, Il2CppClass* right);
    Il2CppClass* (*Metadata_ResolveDheTypeHandleClass_0)(Il2CppClass* klass);
    const Il2CppImage* (*Metadata_GetDheMethodMetadataImage_0)(const MethodInfo* method);
    const MethodInfo* (*Metadata_GetDheCurrentMethodMetadata_0)(const MethodInfo* method);
    Il2CppClass* (*Metadata_GetDheClassInitializationOwner_0)(Il2CppClass* klass);
    Il2CppClass* (*Metadata_GetDheReferenceAllocationClass_0)(Il2CppClass* klass);
    Il2CppClass* (*Metadata_GetDheExecutionClass_0)(Il2CppClass* klass);
    const Il2CppType* (*Metadata_GetDhePublicReferenceType_0)(const Il2CppType* type);
    FieldInfo* (*Metadata_ResolveDheReferenceInstanceField_0)(Il2CppObject* obj, const FieldInfo* field);
    bool (*Metadata_TryGetDheVirtualInvokeData_0)(const Il2CppClass* klass, uint16_t logicalSlot, const VirtualInvokeData*& result);
    bool (*Metadata_TryGetDheVirtualInvokeData_1)(const Il2CppClass* klass, const MethodInfo* method, const VirtualInvokeData*& result);
    bool (*Metadata_TryGetDheVirtualBaseMethod_0)(const MethodInfo* method, bool definition, const MethodInfo*& result);
    bool (*Metadata_TryGetDheVirtualReflectionIdentity_0)(const Il2CppClass* reflectedType, const MethodInfo* method, const MethodInfo*& result);
    bool (*Metadata_TryGetDheInterfaceInvokeData_0)(const Il2CppClass* klass, const Il2CppClass* interfaceType, uint16_t logicalSlot, const VirtualInvokeData*& result);
    bool (*Metadata_TryGetDheReferencedAssemblies_0)(const Il2CppAssembly* assembly, std::vector<const Il2CppAssemblyName*>& references);
    Il2CppClass* (*Metadata_FindDheSupplementalType_0)(const Il2CppImage* image, const char* namespaze, const char* name);
    void (*Metadata_GetDheSupplementalTypes_0)(const Il2CppImage* image, std::vector<const Il2CppClass*>& types);
    Il2CppClass* (*Metadata_GetFirstDheSupplementalNestedType_0)(Il2CppClass* klass, void** iter);
    bool (*Metadata_TryGetNextDheSupplementalNestedType_0)(Il2CppClass* klass, void** iter, Il2CppClass** nestedType);
    const MethodInfo* (*Metadata_GetFirstDheSupplementalMethod_0)(Il2CppClass* klass, void** iter);
    bool (*Metadata_TryGetNextDheSupplementalMethod_0)(Il2CppClass* klass, void** iter, const MethodInfo** method);
    FieldInfo* (*Metadata_GetFirstDheSupplementalField_0)(Il2CppClass* klass, void** iter);
    bool (*Metadata_TryGetNextDheSupplementalField_0)(Il2CppClass* klass, void** iter, FieldInfo** field);
    size_t (*Metadata_GetDheSupplementalFieldCount_0)(Il2CppClass* klass);
    const FieldInfo* (*Metadata_ResolveDheSupplementalField_0)(const FieldInfo* field);
    const Il2CppFieldDefinition* (*Metadata_ResolveDheSupplementalFieldDefinition_0)(const Il2CppType* type, const char* name, const Il2CppType* fieldType);
    size_t (*Metadata_GetDheRemovedMethodCount_0)(Il2CppClass* klass);
    size_t (*Metadata_GetDheSupplementalMethodCount_0)(Il2CppClass* klass);
    bool (*Metadata_IsDheRemovedField_0)(const FieldInfo* field);
    size_t (*Metadata_GetDheRemovedFieldCount_0)(Il2CppClass* klass);
    Il2CppClass* (*Metadata_GetDheLogicalFieldParent_0)(FieldInfo* field);
    bool (*Metadata_IsDheField_0)(const FieldInfo* field);
    bool (*Metadata_IsDheSupplementalInstanceField_0)(const FieldInfo* field);
    bool (*Metadata_TryGetDheSupplementalInstanceFieldValue_0)(Il2CppObject* obj, FieldInfo* field, void* value);
    bool (*Metadata_TrySetDheSupplementalInstanceFieldValue_0)(Il2CppObject* obj, const FieldInfo* field, void* value, bool dereferencePointer);
    bool (*Metadata_TryGetDheSupplementalInstanceFieldAddress_0)(Il2CppObject* obj, const FieldInfo* field, void** address);
    bool (*Metadata_TryGetDheSupplementalInstanceFieldValueObject_0)(Il2CppObject* obj, FieldInfo* field, Il2CppObject** value);
    bool (*Metadata_TrySetDheSupplementalInstanceFieldValueObject_0)(Il2CppObject* obj, FieldInfo* field, Il2CppObject* value);
    bool (*Metadata_HasDheLogicalPropertyView_0)(Il2CppClass* klass);
    const PropertyInfo* (*Metadata_GetFirstDheLogicalProperty_0)(Il2CppClass* klass, void** iter);
    bool (*Metadata_TryGetNextDheLogicalProperty_0)(Il2CppClass* klass, void** iter, const PropertyInfo** property);
    size_t (*Metadata_GetDheLogicalPropertyCount_0)(Il2CppClass* klass);
    const PropertyInfo* (*Metadata_GetDheCustomAttributeProperty_0)(Il2CppClass* klass, uint32_t index);
    const MethodInfo* (*Metadata_ResolveDheMethod_0)(const MethodInfo* method);
    bool (*Metadata_HasDheLogicalEventView_0)(Il2CppClass* klass);
    const EventInfo* (*Metadata_GetFirstDheLogicalEvent_0)(Il2CppClass* klass, void** iter);
    bool (*Metadata_TryGetNextDheLogicalEvent_0)(Il2CppClass* klass, void** iter, const EventInfo** eventInfo);
    size_t (*Metadata_GetDheLogicalEventCount_0)(Il2CppClass* klass);
    bool (*Metadata_TryGetDheCustomAttributeSource_0)(const Il2CppImage* image, uint32_t token, const Il2CppImage*& sourceImage, uint32_t& sourceToken);
    Il2CppClass* (*Runtime_ResolveReferenceAllocationClass_0)(Il2CppClass* klass);
    const void* (*Runtime_GetPublicationIdentity_0)();
    const Il2CppImage* (*Runtime_ResolvePublicAssemblyImage_0)(const Il2CppImage* image);
    Il2CppClass* (*Runtime_SelectReferenceInterfaceIterationClass_0)(Il2CppClass* requested, Il2CppClass* selected, const void* iterator);
    bool (*Runtime_IsDheAssembly_0)(const Il2CppAssembly* assembly);
    bool (*Runtime_IsMutableDheAssembly_0)(const Il2CppAssembly* assembly);
    bool (*Runtime_IsDheModuleInitializationReady_0)(const char* assemblyName);
    bool (*Runtime_IsFrozenAotExecutionSource_0)(const Il2CppAssembly* assembly);
    bool (*Runtime_TryGetVirtualInvokeData_0)(const Il2CppClass* klass, uint16_t logicalSlot, const VirtualInvokeData*& result);
    bool (*Runtime_TryGetVirtualInvokeData_1)(const Il2CppClass* klass, const MethodInfo* method, const VirtualInvokeData*& result);
    bool (*Runtime_TryGetVirtualBaseMethod_0)(const MethodInfo* method, bool definition, const MethodInfo*& result);
    bool (*Runtime_TryGetVirtualReflectionIdentity_0)(const Il2CppClass* reflectedType, const MethodInfo* method, const MethodInfo*& result);
    bool (*Runtime_TryGetInterfaceInvokeData_0)(const Il2CppClass* klass, const Il2CppClass* interfaceType, uint16_t logicalSlot, const VirtualInvokeData*& result);
    bool (*Runtime_IsChangedMethod_0)(const MethodInfo* method);
    bool (*Runtime_IsRemovedMethod_0)(const MethodInfo* method);
    bool (*Runtime_IsRemovedType_0)(const Il2CppClass* klass);
    bool (*Runtime_ShouldDispatchToInterpreter_0)(const MethodInfo* method);
    bool (*Runtime_CanEnterWithBaseAbi_0)(const MethodInfo* method);
    const MethodInfo* (*Runtime_ResolveAotGuardMethodByToken_0)(const char* assemblyName, uint32_t token);
    const MethodInfo* (*Runtime_ResolveMethodByToken_0)(const char* assemblyName, uint32_t token);
    const MethodInfo* (*Runtime_ResolveMethodByNameAndToken_0)(const char* assemblyName, const char* declaringType, const char* methodName, uint32_t parameterCount, uint32_t token);
    const MethodInfo* (*Runtime_ResolveInterpreterMethod_0)(const MethodInfo* baseMethod);
    const MethodInfo* (*Runtime_ResolveCurrentExecutionMethod_0)(const MethodInfo* method);
    const MethodInfo* (*Runtime_ResolveNativeReferenceInvokeMethod_0)(const MethodInfo* method, void* receiver);
    const MethodInfo* (*Runtime_ResolveCurrentReceiverMethod_0)(const MethodInfo* method, void* receiver);
    const MethodInfo* (*Runtime_ResolveInterpreterVirtualMethod_0)(const MethodInfo* method, void* receiver, const MethodInfo* callSignature);
};
static bool Legacy_Metadata_TryCopyDheBoxedValueToCurrent_0(Il2CppObject* value, Il2CppClass* currentClass, void* destination) { return false; }
static Image* Legacy_Metadata_GetUnderlyingInterpreterImage_0(const MethodInfo* methodInfo) { return LegacyInterpreterImage(methodInfo); }
static Image* Legacy_Metadata_GetInterpreterResolveImage_0(const MethodInfo* methodInfo) { return LegacyInterpreterImage(methodInfo); }
static bool Legacy_Metadata_HasDheReflectedParent_0(Il2CppClass* reflectedClass, Il2CppClass* declaringClass) { return false; }
static bool Legacy_Metadata_IsDheEquivalentClass_0(Il2CppClass* left, Il2CppClass* right) { return false; }
static Il2CppClass* Legacy_Metadata_ResolveDheTypeHandleClass_0(Il2CppClass* klass) { return klass; }
static const Il2CppImage* Legacy_Metadata_GetDheMethodMetadataImage_0(const MethodInfo* method) { return method->klass->image; }
static const MethodInfo* Legacy_Metadata_GetDheCurrentMethodMetadata_0(const MethodInfo* method) { return method; }
static Il2CppClass* Legacy_Metadata_GetDheClassInitializationOwner_0(Il2CppClass* klass) { return klass; }
static Il2CppClass* Legacy_Metadata_GetDheReferenceAllocationClass_0(Il2CppClass* klass) { return klass; }
static Il2CppClass* Legacy_Metadata_GetDheExecutionClass_0(Il2CppClass* klass) { return klass; }
static const Il2CppType* Legacy_Metadata_GetDhePublicReferenceType_0(const Il2CppType* type) { return type; }
static FieldInfo* Legacy_Metadata_ResolveDheReferenceInstanceField_0(Il2CppObject* obj, const FieldInfo* field) { return const_cast<FieldInfo*>(field); }
static bool Legacy_Metadata_TryGetDheVirtualInvokeData_0(const Il2CppClass* klass, uint16_t logicalSlot, const VirtualInvokeData*& result) { return false; }
static bool Legacy_Metadata_TryGetDheVirtualInvokeData_1(const Il2CppClass* klass, const MethodInfo* method, const VirtualInvokeData*& result) { return false; }
static bool Legacy_Metadata_TryGetDheVirtualBaseMethod_0(const MethodInfo* method, bool definition, const MethodInfo*& result) { return false; }
static bool Legacy_Metadata_TryGetDheVirtualReflectionIdentity_0(const Il2CppClass* reflectedType, const MethodInfo* method, const MethodInfo*& result) { return false; }
static bool Legacy_Metadata_TryGetDheInterfaceInvokeData_0(const Il2CppClass* klass, const Il2CppClass* interfaceType, uint16_t logicalSlot, const VirtualInvokeData*& result) { return false; }
static bool Legacy_Metadata_TryGetDheReferencedAssemblies_0(const Il2CppAssembly* assembly, std::vector<const Il2CppAssemblyName*>& references) { return false; }
static Il2CppClass* Legacy_Metadata_FindDheSupplementalType_0(const Il2CppImage* image, const char* namespaze, const char* name) { return nullptr; }
static void Legacy_Metadata_GetDheSupplementalTypes_0(const Il2CppImage* image, std::vector<const Il2CppClass*>& types) {  }
static Il2CppClass* Legacy_Metadata_GetFirstDheSupplementalNestedType_0(Il2CppClass* klass, void** iter) { return nullptr; }
static bool Legacy_Metadata_TryGetNextDheSupplementalNestedType_0(Il2CppClass* klass, void** iter, Il2CppClass** nestedType) { return false; }
static const MethodInfo* Legacy_Metadata_GetFirstDheSupplementalMethod_0(Il2CppClass* klass, void** iter) { return nullptr; }
static bool Legacy_Metadata_TryGetNextDheSupplementalMethod_0(Il2CppClass* klass, void** iter, const MethodInfo** method) { return false; }
static FieldInfo* Legacy_Metadata_GetFirstDheSupplementalField_0(Il2CppClass* klass, void** iter) { return nullptr; }
static bool Legacy_Metadata_TryGetNextDheSupplementalField_0(Il2CppClass* klass, void** iter, FieldInfo** field) { return false; }
static size_t Legacy_Metadata_GetDheSupplementalFieldCount_0(Il2CppClass* klass) { return 0; }
static const FieldInfo* Legacy_Metadata_ResolveDheSupplementalField_0(const FieldInfo* field) { return field; }
static const Il2CppFieldDefinition* Legacy_Metadata_ResolveDheSupplementalFieldDefinition_0(const Il2CppType* type, const char* name, const Il2CppType* fieldType) { return nullptr; }
static size_t Legacy_Metadata_GetDheRemovedMethodCount_0(Il2CppClass* klass) { return 0; }
static size_t Legacy_Metadata_GetDheSupplementalMethodCount_0(Il2CppClass* klass) { return 0; }
static bool Legacy_Metadata_IsDheRemovedField_0(const FieldInfo* field) { return false; }
static size_t Legacy_Metadata_GetDheRemovedFieldCount_0(Il2CppClass* klass) { return 0; }
static Il2CppClass* Legacy_Metadata_GetDheLogicalFieldParent_0(FieldInfo* field) { return field ? field->parent : nullptr; }
static bool Legacy_Metadata_IsDheField_0(const FieldInfo* field) { return false; }
static bool Legacy_Metadata_IsDheSupplementalInstanceField_0(const FieldInfo* field) { return false; }
static bool Legacy_Metadata_TryGetDheSupplementalInstanceFieldValue_0(Il2CppObject* obj, FieldInfo* field, void* value) { return false; }
static bool Legacy_Metadata_TrySetDheSupplementalInstanceFieldValue_0(Il2CppObject* obj, const FieldInfo* field, void* value, bool dereferencePointer) { return false; }
static bool Legacy_Metadata_TryGetDheSupplementalInstanceFieldAddress_0(Il2CppObject* obj, const FieldInfo* field, void** address) { return false; }
static bool Legacy_Metadata_TryGetDheSupplementalInstanceFieldValueObject_0(Il2CppObject* obj, FieldInfo* field, Il2CppObject** value) { return false; }
static bool Legacy_Metadata_TrySetDheSupplementalInstanceFieldValueObject_0(Il2CppObject* obj, FieldInfo* field, Il2CppObject* value) { return false; }
static bool Legacy_Metadata_HasDheLogicalPropertyView_0(Il2CppClass* klass) { return false; }
static const PropertyInfo* Legacy_Metadata_GetFirstDheLogicalProperty_0(Il2CppClass* klass, void** iter) { return nullptr; }
static bool Legacy_Metadata_TryGetNextDheLogicalProperty_0(Il2CppClass* klass, void** iter, const PropertyInfo** property) { return false; }
static size_t Legacy_Metadata_GetDheLogicalPropertyCount_0(Il2CppClass* klass) { return 0; }
static const PropertyInfo* Legacy_Metadata_GetDheCustomAttributeProperty_0(Il2CppClass* klass, uint32_t index) { return LegacyProperty(klass, index); }
static const MethodInfo* Legacy_Metadata_ResolveDheMethod_0(const MethodInfo* method) { return method; }
static bool Legacy_Metadata_HasDheLogicalEventView_0(Il2CppClass* klass) { return false; }
static const EventInfo* Legacy_Metadata_GetFirstDheLogicalEvent_0(Il2CppClass* klass, void** iter) { return nullptr; }
static bool Legacy_Metadata_TryGetNextDheLogicalEvent_0(Il2CppClass* klass, void** iter, const EventInfo** eventInfo) { return false; }
static size_t Legacy_Metadata_GetDheLogicalEventCount_0(Il2CppClass* klass) { return 0; }
static bool Legacy_Metadata_TryGetDheCustomAttributeSource_0(const Il2CppImage* image, uint32_t token, const Il2CppImage*& sourceImage, uint32_t& sourceToken) { return false; }
static Il2CppClass* Legacy_Runtime_ResolveReferenceAllocationClass_0(Il2CppClass* klass) { return klass; }
static const void* Legacy_Runtime_GetPublicationIdentity_0() { return nullptr; }
static const Il2CppImage* Legacy_Runtime_ResolvePublicAssemblyImage_0(const Il2CppImage* image) { return image; }
static Il2CppClass* Legacy_Runtime_SelectReferenceInterfaceIterationClass_0(Il2CppClass* requested, Il2CppClass* selected, const void* iterator) { return requested; }
static bool Legacy_Runtime_IsDheAssembly_0(const Il2CppAssembly* assembly) { return false; }
static bool Legacy_Runtime_IsMutableDheAssembly_0(const Il2CppAssembly* assembly) { return false; }
static bool Legacy_Runtime_IsDheModuleInitializationReady_0(const char* assemblyName) { return false; }
static bool Legacy_Runtime_IsFrozenAotExecutionSource_0(const Il2CppAssembly* assembly) { return false; }
static bool Legacy_Runtime_TryGetVirtualInvokeData_0(const Il2CppClass* klass, uint16_t logicalSlot, const VirtualInvokeData*& result) { return false; }
static bool Legacy_Runtime_TryGetVirtualInvokeData_1(const Il2CppClass* klass, const MethodInfo* method, const VirtualInvokeData*& result) { return false; }
static bool Legacy_Runtime_TryGetVirtualBaseMethod_0(const MethodInfo* method, bool definition, const MethodInfo*& result) { return false; }
static bool Legacy_Runtime_TryGetVirtualReflectionIdentity_0(const Il2CppClass* reflectedType, const MethodInfo* method, const MethodInfo*& result) { return false; }
static bool Legacy_Runtime_TryGetInterfaceInvokeData_0(const Il2CppClass* klass, const Il2CppClass* interfaceType, uint16_t logicalSlot, const VirtualInvokeData*& result) { return false; }
static bool Legacy_Runtime_IsChangedMethod_0(const MethodInfo* method) { return false; }
static bool Legacy_Runtime_IsRemovedMethod_0(const MethodInfo* method) { return false; }
static bool Legacy_Runtime_IsRemovedType_0(const Il2CppClass* klass) { return false; }
static bool Legacy_Runtime_ShouldDispatchToInterpreter_0(const MethodInfo* method) { return false; }
static bool Legacy_Runtime_CanEnterWithBaseAbi_0(const MethodInfo* method) { return true; }
static const MethodInfo* Legacy_Runtime_ResolveAotGuardMethodByToken_0(const char* assemblyName, uint32_t token) { return nullptr; }
static const MethodInfo* Legacy_Runtime_ResolveMethodByToken_0(const char* assemblyName, uint32_t token) { return nullptr; }
static const MethodInfo* Legacy_Runtime_ResolveMethodByNameAndToken_0(const char* assemblyName, const char* declaringType, const char* methodName, uint32_t parameterCount, uint32_t token) { return nullptr; }
static const MethodInfo* Legacy_Runtime_ResolveInterpreterMethod_0(const MethodInfo* baseMethod) { return baseMethod; }
static const MethodInfo* Legacy_Runtime_ResolveCurrentExecutionMethod_0(const MethodInfo* method) { return method; }
static const MethodInfo* Legacy_Runtime_ResolveNativeReferenceInvokeMethod_0(const MethodInfo* method, void* receiver) { return method; }
static const MethodInfo* Legacy_Runtime_ResolveCurrentReceiverMethod_0(const MethodInfo* method, void* receiver) { return method; }
static const MethodInfo* Legacy_Runtime_ResolveInterpreterVirtualMethod_0(const MethodInfo* method, void* receiver, const MethodInfo* callSignature) { return method; }
static const HookTable legacyTable = {
    2,
    &Legacy_Metadata_TryCopyDheBoxedValueToCurrent_0,
    &Legacy_Metadata_GetUnderlyingInterpreterImage_0,
    &Legacy_Metadata_GetInterpreterResolveImage_0,
    &Legacy_Metadata_HasDheReflectedParent_0,
    &Legacy_Metadata_IsDheEquivalentClass_0,
    &Legacy_Metadata_ResolveDheTypeHandleClass_0,
    &Legacy_Metadata_GetDheMethodMetadataImage_0,
    &Legacy_Metadata_GetDheCurrentMethodMetadata_0,
    &Legacy_Metadata_GetDheClassInitializationOwner_0,
    &Legacy_Metadata_GetDheReferenceAllocationClass_0,
    &Legacy_Metadata_GetDheExecutionClass_0,
    &Legacy_Metadata_GetDhePublicReferenceType_0,
    &Legacy_Metadata_ResolveDheReferenceInstanceField_0,
    &Legacy_Metadata_TryGetDheVirtualInvokeData_0,
    &Legacy_Metadata_TryGetDheVirtualInvokeData_1,
    &Legacy_Metadata_TryGetDheVirtualBaseMethod_0,
    &Legacy_Metadata_TryGetDheVirtualReflectionIdentity_0,
    &Legacy_Metadata_TryGetDheInterfaceInvokeData_0,
    &Legacy_Metadata_TryGetDheReferencedAssemblies_0,
    &Legacy_Metadata_FindDheSupplementalType_0,
    &Legacy_Metadata_GetDheSupplementalTypes_0,
    &Legacy_Metadata_GetFirstDheSupplementalNestedType_0,
    &Legacy_Metadata_TryGetNextDheSupplementalNestedType_0,
    &Legacy_Metadata_GetFirstDheSupplementalMethod_0,
    &Legacy_Metadata_TryGetNextDheSupplementalMethod_0,
    &Legacy_Metadata_GetFirstDheSupplementalField_0,
    &Legacy_Metadata_TryGetNextDheSupplementalField_0,
    &Legacy_Metadata_GetDheSupplementalFieldCount_0,
    &Legacy_Metadata_ResolveDheSupplementalField_0,
    &Legacy_Metadata_ResolveDheSupplementalFieldDefinition_0,
    &Legacy_Metadata_GetDheRemovedMethodCount_0,
    &Legacy_Metadata_GetDheSupplementalMethodCount_0,
    &Legacy_Metadata_IsDheRemovedField_0,
    &Legacy_Metadata_GetDheRemovedFieldCount_0,
    &Legacy_Metadata_GetDheLogicalFieldParent_0,
    &Legacy_Metadata_IsDheField_0,
    &Legacy_Metadata_IsDheSupplementalInstanceField_0,
    &Legacy_Metadata_TryGetDheSupplementalInstanceFieldValue_0,
    &Legacy_Metadata_TrySetDheSupplementalInstanceFieldValue_0,
    &Legacy_Metadata_TryGetDheSupplementalInstanceFieldAddress_0,
    &Legacy_Metadata_TryGetDheSupplementalInstanceFieldValueObject_0,
    &Legacy_Metadata_TrySetDheSupplementalInstanceFieldValueObject_0,
    &Legacy_Metadata_HasDheLogicalPropertyView_0,
    &Legacy_Metadata_GetFirstDheLogicalProperty_0,
    &Legacy_Metadata_TryGetNextDheLogicalProperty_0,
    &Legacy_Metadata_GetDheLogicalPropertyCount_0,
    &Legacy_Metadata_GetDheCustomAttributeProperty_0,
    &Legacy_Metadata_ResolveDheMethod_0,
    &Legacy_Metadata_HasDheLogicalEventView_0,
    &Legacy_Metadata_GetFirstDheLogicalEvent_0,
    &Legacy_Metadata_TryGetNextDheLogicalEvent_0,
    &Legacy_Metadata_GetDheLogicalEventCount_0,
    &Legacy_Metadata_TryGetDheCustomAttributeSource_0,
    &Legacy_Runtime_ResolveReferenceAllocationClass_0,
    &Legacy_Runtime_GetPublicationIdentity_0,
    &Legacy_Runtime_ResolvePublicAssemblyImage_0,
    &Legacy_Runtime_SelectReferenceInterfaceIterationClass_0,
    &Legacy_Runtime_IsDheAssembly_0,
    &Legacy_Runtime_IsMutableDheAssembly_0,
    &Legacy_Runtime_IsDheModuleInitializationReady_0,
    &Legacy_Runtime_IsFrozenAotExecutionSource_0,
    &Legacy_Runtime_TryGetVirtualInvokeData_0,
    &Legacy_Runtime_TryGetVirtualInvokeData_1,
    &Legacy_Runtime_TryGetVirtualBaseMethod_0,
    &Legacy_Runtime_TryGetVirtualReflectionIdentity_0,
    &Legacy_Runtime_TryGetInterfaceInvokeData_0,
    &Legacy_Runtime_IsChangedMethod_0,
    &Legacy_Runtime_IsRemovedMethod_0,
    &Legacy_Runtime_IsRemovedType_0,
    &Legacy_Runtime_ShouldDispatchToInterpreter_0,
    &Legacy_Runtime_CanEnterWithBaseAbi_0,
    &Legacy_Runtime_ResolveAotGuardMethodByToken_0,
    &Legacy_Runtime_ResolveMethodByToken_0,
    &Legacy_Runtime_ResolveMethodByNameAndToken_0,
    &Legacy_Runtime_ResolveInterpreterMethod_0,
    &Legacy_Runtime_ResolveCurrentExecutionMethod_0,
    &Legacy_Runtime_ResolveNativeReferenceInvokeMethod_0,
    &Legacy_Runtime_ResolveCurrentReceiverMethod_0,
    &Legacy_Runtime_ResolveInterpreterVirtualMethod_0
};
static const HookTable dheTable = {
    1,
    &hybridclr::metadata::MetadataModule::DheImpl_TryCopyDheBoxedValueToCurrent,
    &hybridclr::metadata::MetadataModule::DheImpl_GetUnderlyingInterpreterImage,
    &hybridclr::metadata::MetadataModule::DheImpl_GetInterpreterResolveImage,
    &hybridclr::metadata::MetadataModule::DheImpl_HasDheReflectedParent,
    &hybridclr::metadata::MetadataModule::DheImpl_IsDheEquivalentClass,
    &hybridclr::metadata::MetadataModule::DheImpl_ResolveDheTypeHandleClass,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheMethodMetadataImage,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheCurrentMethodMetadata,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheClassInitializationOwner,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheReferenceAllocationClass,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheExecutionClass,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDhePublicReferenceType,
    &hybridclr::metadata::MetadataModule::DheImpl_ResolveDheReferenceInstanceField,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheVirtualInvokeData,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheVirtualInvokeData,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheVirtualBaseMethod,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheVirtualReflectionIdentity,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheInterfaceInvokeData,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheReferencedAssemblies,
    &hybridclr::metadata::MetadataModule::DheImpl_FindDheSupplementalType,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheSupplementalTypes,
    &hybridclr::metadata::MetadataModule::DheImpl_GetFirstDheSupplementalNestedType,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetNextDheSupplementalNestedType,
    &hybridclr::metadata::MetadataModule::DheImpl_GetFirstDheSupplementalMethod,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetNextDheSupplementalMethod,
    &hybridclr::metadata::MetadataModule::DheImpl_GetFirstDheSupplementalField,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetNextDheSupplementalField,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheSupplementalFieldCount,
    &hybridclr::metadata::MetadataModule::DheImpl_ResolveDheSupplementalField,
    &hybridclr::metadata::MetadataModule::DheImpl_ResolveDheSupplementalFieldDefinition,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheRemovedMethodCount,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheSupplementalMethodCount,
    &hybridclr::metadata::MetadataModule::DheImpl_IsDheRemovedField,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheRemovedFieldCount,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheLogicalFieldParent,
    &hybridclr::metadata::MetadataModule::DheImpl_IsDheField,
    &hybridclr::metadata::MetadataModule::DheImpl_IsDheSupplementalInstanceField,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheSupplementalInstanceFieldValue,
    &hybridclr::metadata::MetadataModule::DheImpl_TrySetDheSupplementalInstanceFieldValue,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheSupplementalInstanceFieldAddress,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheSupplementalInstanceFieldValueObject,
    &hybridclr::metadata::MetadataModule::DheImpl_TrySetDheSupplementalInstanceFieldValueObject,
    &hybridclr::metadata::MetadataModule::DheImpl_HasDheLogicalPropertyView,
    &hybridclr::metadata::MetadataModule::DheImpl_GetFirstDheLogicalProperty,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetNextDheLogicalProperty,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheLogicalPropertyCount,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheCustomAttributeProperty,
    &hybridclr::metadata::MetadataModule::DheImpl_ResolveDheMethod,
    &hybridclr::metadata::MetadataModule::DheImpl_HasDheLogicalEventView,
    &hybridclr::metadata::MetadataModule::DheImpl_GetFirstDheLogicalEvent,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetNextDheLogicalEvent,
    &hybridclr::metadata::MetadataModule::DheImpl_GetDheLogicalEventCount,
    &hybridclr::metadata::MetadataModule::DheImpl_TryGetDheCustomAttributeSource,
    &hybridclr::dhe::DheImpl_ResolveReferenceAllocationClass,
    &hybridclr::dhe::DheImpl_GetPublicationIdentity,
    &hybridclr::dhe::DheImpl_ResolvePublicAssemblyImage,
    &hybridclr::dhe::DheImpl_SelectReferenceInterfaceIterationClass,
    &hybridclr::dhe::DheImpl_IsDheAssembly,
    &hybridclr::dhe::DheImpl_IsMutableDheAssembly,
    &hybridclr::dhe::DheImpl_IsDheModuleInitializationReady,
    &hybridclr::dhe::DheImpl_IsFrozenAotExecutionSource,
    &hybridclr::dhe::DheImpl_TryGetVirtualInvokeData,
    &hybridclr::dhe::DheImpl_TryGetVirtualInvokeData,
    &hybridclr::dhe::DheImpl_TryGetVirtualBaseMethod,
    &hybridclr::dhe::DheImpl_TryGetVirtualReflectionIdentity,
    &hybridclr::dhe::DheImpl_TryGetInterfaceInvokeData,
    &hybridclr::dhe::DheImpl_IsChangedMethod,
    &hybridclr::dhe::DheImpl_IsRemovedMethod,
    &hybridclr::dhe::DheImpl_IsRemovedType,
    &hybridclr::dhe::DheImpl_ShouldDispatchToInterpreter,
    &hybridclr::dhe::DheImpl_CanEnterWithBaseAbi,
    &hybridclr::dhe::DheImpl_ResolveAotGuardMethodByToken,
    &hybridclr::dhe::DheImpl_ResolveMethodByToken,
    &hybridclr::dhe::DheImpl_ResolveMethodByNameAndToken,
    &hybridclr::dhe::DheImpl_ResolveInterpreterMethod,
    &hybridclr::dhe::DheImpl_ResolveCurrentExecutionMethod,
    &hybridclr::dhe::DheImpl_ResolveNativeReferenceInvokeMethod,
    &hybridclr::dhe::DheImpl_ResolveCurrentReceiverMethod,
    &hybridclr::dhe::DheImpl_ResolveInterpreterVirtualMethod
};
static const HookTable unselectedTable = {
    0,
    &Legacy_Metadata_TryCopyDheBoxedValueToCurrent_0,
    &Legacy_Metadata_GetUnderlyingInterpreterImage_0,
    &Legacy_Metadata_GetInterpreterResolveImage_0,
    &Legacy_Metadata_HasDheReflectedParent_0,
    &Legacy_Metadata_IsDheEquivalentClass_0,
    &Legacy_Metadata_ResolveDheTypeHandleClass_0,
    &Legacy_Metadata_GetDheMethodMetadataImage_0,
    &Legacy_Metadata_GetDheCurrentMethodMetadata_0,
    &Legacy_Metadata_GetDheClassInitializationOwner_0,
    &Legacy_Metadata_GetDheReferenceAllocationClass_0,
    &Legacy_Metadata_GetDheExecutionClass_0,
    &Legacy_Metadata_GetDhePublicReferenceType_0,
    &Legacy_Metadata_ResolveDheReferenceInstanceField_0,
    &Legacy_Metadata_TryGetDheVirtualInvokeData_0,
    &Legacy_Metadata_TryGetDheVirtualInvokeData_1,
    &Legacy_Metadata_TryGetDheVirtualBaseMethod_0,
    &Legacy_Metadata_TryGetDheVirtualReflectionIdentity_0,
    &Legacy_Metadata_TryGetDheInterfaceInvokeData_0,
    &Legacy_Metadata_TryGetDheReferencedAssemblies_0,
    &Legacy_Metadata_FindDheSupplementalType_0,
    &Legacy_Metadata_GetDheSupplementalTypes_0,
    &Legacy_Metadata_GetFirstDheSupplementalNestedType_0,
    &Legacy_Metadata_TryGetNextDheSupplementalNestedType_0,
    &Legacy_Metadata_GetFirstDheSupplementalMethod_0,
    &Legacy_Metadata_TryGetNextDheSupplementalMethod_0,
    &Legacy_Metadata_GetFirstDheSupplementalField_0,
    &Legacy_Metadata_TryGetNextDheSupplementalField_0,
    &Legacy_Metadata_GetDheSupplementalFieldCount_0,
    &Legacy_Metadata_ResolveDheSupplementalField_0,
    &Legacy_Metadata_ResolveDheSupplementalFieldDefinition_0,
    &Legacy_Metadata_GetDheRemovedMethodCount_0,
    &Legacy_Metadata_GetDheSupplementalMethodCount_0,
    &Legacy_Metadata_IsDheRemovedField_0,
    &Legacy_Metadata_GetDheRemovedFieldCount_0,
    &Legacy_Metadata_GetDheLogicalFieldParent_0,
    &Legacy_Metadata_IsDheField_0,
    &Legacy_Metadata_IsDheSupplementalInstanceField_0,
    &Legacy_Metadata_TryGetDheSupplementalInstanceFieldValue_0,
    &Legacy_Metadata_TrySetDheSupplementalInstanceFieldValue_0,
    &Legacy_Metadata_TryGetDheSupplementalInstanceFieldAddress_0,
    &Legacy_Metadata_TryGetDheSupplementalInstanceFieldValueObject_0,
    &Legacy_Metadata_TrySetDheSupplementalInstanceFieldValueObject_0,
    &Legacy_Metadata_HasDheLogicalPropertyView_0,
    &Legacy_Metadata_GetFirstDheLogicalProperty_0,
    &Legacy_Metadata_TryGetNextDheLogicalProperty_0,
    &Legacy_Metadata_GetDheLogicalPropertyCount_0,
    &Legacy_Metadata_GetDheCustomAttributeProperty_0,
    &Legacy_Metadata_ResolveDheMethod_0,
    &Legacy_Metadata_HasDheLogicalEventView_0,
    &Legacy_Metadata_GetFirstDheLogicalEvent_0,
    &Legacy_Metadata_TryGetNextDheLogicalEvent_0,
    &Legacy_Metadata_GetDheLogicalEventCount_0,
    &Legacy_Metadata_TryGetDheCustomAttributeSource_0,
    &Legacy_Runtime_ResolveReferenceAllocationClass_0,
    &Legacy_Runtime_GetPublicationIdentity_0,
    &Legacy_Runtime_ResolvePublicAssemblyImage_0,
    &Legacy_Runtime_SelectReferenceInterfaceIterationClass_0,
    &Legacy_Runtime_IsDheAssembly_0,
    &Legacy_Runtime_IsMutableDheAssembly_0,
    &Legacy_Runtime_IsDheModuleInitializationReady_0,
    &Legacy_Runtime_IsFrozenAotExecutionSource_0,
    &Legacy_Runtime_TryGetVirtualInvokeData_0,
    &Legacy_Runtime_TryGetVirtualInvokeData_1,
    &Legacy_Runtime_TryGetVirtualBaseMethod_0,
    &Legacy_Runtime_TryGetVirtualReflectionIdentity_0,
    &Legacy_Runtime_TryGetInterfaceInvokeData_0,
    &Legacy_Runtime_IsChangedMethod_0,
    &Legacy_Runtime_IsRemovedMethod_0,
    &Legacy_Runtime_IsRemovedType_0,
    &Legacy_Runtime_ShouldDispatchToInterpreter_0,
    &Legacy_Runtime_CanEnterWithBaseAbi_0,
    &Legacy_Runtime_ResolveAotGuardMethodByToken_0,
    &Legacy_Runtime_ResolveMethodByToken_0,
    &Legacy_Runtime_ResolveMethodByNameAndToken_0,
    &Legacy_Runtime_ResolveInterpreterMethod_0,
    &Legacy_Runtime_ResolveCurrentExecutionMethod_0,
    &Legacy_Runtime_ResolveNativeReferenceInvokeMethod_0,
    &Legacy_Runtime_ResolveCurrentReceiverMethod_0,
    &Legacy_Runtime_ResolveInterpreterVirtualMethod_0
};
static std::atomic<const HookTable*> selectedHooks{&unselectedTable};
int BindMode(int mode) {
    if (mode != 1 && mode != 2) return 2;
    if (selectedHooks.load(std::memory_order_acquire)->mode) return 1;
    selectedHooks.store(mode == 1 ? &dheTable : &legacyTable, std::memory_order_release);
    return 0;
}
int GetMode() { return selectedHooks.load(std::memory_order_acquire)->mode; }
static const HookTable& GetHooks() { return *selectedHooks.load(std::memory_order_acquire); }
}}
bool hybridclr::metadata::MetadataModule::TryCopyDheBoxedValueToCurrent(Il2CppObject* value, Il2CppClass* currentClass, void* destination) { return hybridclr::startup::GetHooks().Metadata_TryCopyDheBoxedValueToCurrent_0(value, currentClass, destination); }
Image* hybridclr::metadata::MetadataModule::GetUnderlyingInterpreterImage(const MethodInfo* methodInfo) { return hybridclr::startup::GetHooks().Metadata_GetUnderlyingInterpreterImage_0(methodInfo); }
Image* hybridclr::metadata::MetadataModule::GetInterpreterResolveImage(const MethodInfo* methodInfo) { return hybridclr::startup::GetHooks().Metadata_GetInterpreterResolveImage_0(methodInfo); }
bool hybridclr::metadata::MetadataModule::HasDheReflectedParent(Il2CppClass* reflectedClass, Il2CppClass* declaringClass) { return hybridclr::startup::GetHooks().Metadata_HasDheReflectedParent_0(reflectedClass, declaringClass); }
bool hybridclr::metadata::MetadataModule::IsDheEquivalentClass(Il2CppClass* left, Il2CppClass* right) { return hybridclr::startup::GetHooks().Metadata_IsDheEquivalentClass_0(left, right); }
Il2CppClass* hybridclr::metadata::MetadataModule::ResolveDheTypeHandleClass(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_ResolveDheTypeHandleClass_0(klass); }
const Il2CppImage* hybridclr::metadata::MetadataModule::GetDheMethodMetadataImage(const MethodInfo* method) { return hybridclr::startup::GetHooks().Metadata_GetDheMethodMetadataImage_0(method); }
const MethodInfo* hybridclr::metadata::MetadataModule::GetDheCurrentMethodMetadata(const MethodInfo* method) { return hybridclr::startup::GetHooks().Metadata_GetDheCurrentMethodMetadata_0(method); }
Il2CppClass* hybridclr::metadata::MetadataModule::GetDheClassInitializationOwner(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheClassInitializationOwner_0(klass); }
Il2CppClass* hybridclr::metadata::MetadataModule::GetDheReferenceAllocationClass(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheReferenceAllocationClass_0(klass); }
Il2CppClass* hybridclr::metadata::MetadataModule::GetDheExecutionClass(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheExecutionClass_0(klass); }
const Il2CppType* hybridclr::metadata::MetadataModule::GetDhePublicReferenceType(const Il2CppType* type) { return hybridclr::startup::GetHooks().Metadata_GetDhePublicReferenceType_0(type); }
FieldInfo* hybridclr::metadata::MetadataModule::ResolveDheReferenceInstanceField(Il2CppObject* obj, const FieldInfo* field) { return hybridclr::startup::GetHooks().Metadata_ResolveDheReferenceInstanceField_0(obj, field); }
bool hybridclr::metadata::MetadataModule::TryGetDheVirtualInvokeData(const Il2CppClass* klass, uint16_t logicalSlot, const VirtualInvokeData*& result) { return hybridclr::startup::GetHooks().Metadata_TryGetDheVirtualInvokeData_0(klass, logicalSlot, result); }
bool hybridclr::metadata::MetadataModule::TryGetDheVirtualInvokeData(const Il2CppClass* klass, const MethodInfo* method, const VirtualInvokeData*& result) { return hybridclr::startup::GetHooks().Metadata_TryGetDheVirtualInvokeData_1(klass, method, result); }
bool hybridclr::metadata::MetadataModule::TryGetDheVirtualBaseMethod(const MethodInfo* method, bool definition, const MethodInfo*& result) { return hybridclr::startup::GetHooks().Metadata_TryGetDheVirtualBaseMethod_0(method, definition, result); }
bool hybridclr::metadata::MetadataModule::TryGetDheVirtualReflectionIdentity(const Il2CppClass* reflectedType, const MethodInfo* method, const MethodInfo*& result) { return hybridclr::startup::GetHooks().Metadata_TryGetDheVirtualReflectionIdentity_0(reflectedType, method, result); }
bool hybridclr::metadata::MetadataModule::TryGetDheInterfaceInvokeData(const Il2CppClass* klass, const Il2CppClass* interfaceType, uint16_t logicalSlot, const VirtualInvokeData*& result) { return hybridclr::startup::GetHooks().Metadata_TryGetDheInterfaceInvokeData_0(klass, interfaceType, logicalSlot, result); }
bool hybridclr::metadata::MetadataModule::TryGetDheReferencedAssemblies(const Il2CppAssembly* assembly, std::vector<const Il2CppAssemblyName*>& references) { return hybridclr::startup::GetHooks().Metadata_TryGetDheReferencedAssemblies_0(assembly, references); }
Il2CppClass* hybridclr::metadata::MetadataModule::FindDheSupplementalType(const Il2CppImage* image, const char* namespaze, const char* name) { return hybridclr::startup::GetHooks().Metadata_FindDheSupplementalType_0(image, namespaze, name); }
void hybridclr::metadata::MetadataModule::GetDheSupplementalTypes(const Il2CppImage* image, std::vector<const Il2CppClass*>& types) { return hybridclr::startup::GetHooks().Metadata_GetDheSupplementalTypes_0(image, types); }
Il2CppClass* hybridclr::metadata::MetadataModule::GetFirstDheSupplementalNestedType(Il2CppClass* klass, void** iter) { return hybridclr::startup::GetHooks().Metadata_GetFirstDheSupplementalNestedType_0(klass, iter); }
bool hybridclr::metadata::MetadataModule::TryGetNextDheSupplementalNestedType(Il2CppClass* klass, void** iter, Il2CppClass** nestedType) { return hybridclr::startup::GetHooks().Metadata_TryGetNextDheSupplementalNestedType_0(klass, iter, nestedType); }
const MethodInfo* hybridclr::metadata::MetadataModule::GetFirstDheSupplementalMethod(Il2CppClass* klass, void** iter) { return hybridclr::startup::GetHooks().Metadata_GetFirstDheSupplementalMethod_0(klass, iter); }
bool hybridclr::metadata::MetadataModule::TryGetNextDheSupplementalMethod(Il2CppClass* klass, void** iter, const MethodInfo** method) { return hybridclr::startup::GetHooks().Metadata_TryGetNextDheSupplementalMethod_0(klass, iter, method); }
FieldInfo* hybridclr::metadata::MetadataModule::GetFirstDheSupplementalField(Il2CppClass* klass, void** iter) { return hybridclr::startup::GetHooks().Metadata_GetFirstDheSupplementalField_0(klass, iter); }
bool hybridclr::metadata::MetadataModule::TryGetNextDheSupplementalField(Il2CppClass* klass, void** iter, FieldInfo** field) { return hybridclr::startup::GetHooks().Metadata_TryGetNextDheSupplementalField_0(klass, iter, field); }
size_t hybridclr::metadata::MetadataModule::GetDheSupplementalFieldCount(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheSupplementalFieldCount_0(klass); }
const FieldInfo* hybridclr::metadata::MetadataModule::ResolveDheSupplementalField(const FieldInfo* field) { return hybridclr::startup::GetHooks().Metadata_ResolveDheSupplementalField_0(field); }
const Il2CppFieldDefinition* hybridclr::metadata::MetadataModule::ResolveDheSupplementalFieldDefinition(const Il2CppType* type, const char* name, const Il2CppType* fieldType) { return hybridclr::startup::GetHooks().Metadata_ResolveDheSupplementalFieldDefinition_0(type, name, fieldType); }
size_t hybridclr::metadata::MetadataModule::GetDheRemovedMethodCount(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheRemovedMethodCount_0(klass); }
size_t hybridclr::metadata::MetadataModule::GetDheSupplementalMethodCount(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheSupplementalMethodCount_0(klass); }
bool hybridclr::metadata::MetadataModule::IsDheRemovedField(const FieldInfo* field) { return hybridclr::startup::GetHooks().Metadata_IsDheRemovedField_0(field); }
size_t hybridclr::metadata::MetadataModule::GetDheRemovedFieldCount(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheRemovedFieldCount_0(klass); }
Il2CppClass* hybridclr::metadata::MetadataModule::GetDheLogicalFieldParent(FieldInfo* field) { return hybridclr::startup::GetHooks().Metadata_GetDheLogicalFieldParent_0(field); }
bool hybridclr::metadata::MetadataModule::IsDheField(const FieldInfo* field) { return hybridclr::startup::GetHooks().Metadata_IsDheField_0(field); }
bool hybridclr::metadata::MetadataModule::IsDheSupplementalInstanceField(const FieldInfo* field) { return hybridclr::startup::GetHooks().Metadata_IsDheSupplementalInstanceField_0(field); }
bool hybridclr::metadata::MetadataModule::TryGetDheSupplementalInstanceFieldValue(Il2CppObject* obj, FieldInfo* field, void* value) { return hybridclr::startup::GetHooks().Metadata_TryGetDheSupplementalInstanceFieldValue_0(obj, field, value); }
bool hybridclr::metadata::MetadataModule::TrySetDheSupplementalInstanceFieldValue(Il2CppObject* obj, const FieldInfo* field, void* value, bool dereferencePointer) { return hybridclr::startup::GetHooks().Metadata_TrySetDheSupplementalInstanceFieldValue_0(obj, field, value, dereferencePointer); }
bool hybridclr::metadata::MetadataModule::TryGetDheSupplementalInstanceFieldAddress(Il2CppObject* obj, const FieldInfo* field, void** address) { return hybridclr::startup::GetHooks().Metadata_TryGetDheSupplementalInstanceFieldAddress_0(obj, field, address); }
bool hybridclr::metadata::MetadataModule::TryGetDheSupplementalInstanceFieldValueObject(Il2CppObject* obj, FieldInfo* field, Il2CppObject** value) { return hybridclr::startup::GetHooks().Metadata_TryGetDheSupplementalInstanceFieldValueObject_0(obj, field, value); }
bool hybridclr::metadata::MetadataModule::TrySetDheSupplementalInstanceFieldValueObject(Il2CppObject* obj, FieldInfo* field, Il2CppObject* value) { return hybridclr::startup::GetHooks().Metadata_TrySetDheSupplementalInstanceFieldValueObject_0(obj, field, value); }
bool hybridclr::metadata::MetadataModule::HasDheLogicalPropertyView(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_HasDheLogicalPropertyView_0(klass); }
const PropertyInfo* hybridclr::metadata::MetadataModule::GetFirstDheLogicalProperty(Il2CppClass* klass, void** iter) { return hybridclr::startup::GetHooks().Metadata_GetFirstDheLogicalProperty_0(klass, iter); }
bool hybridclr::metadata::MetadataModule::TryGetNextDheLogicalProperty(Il2CppClass* klass, void** iter, const PropertyInfo** property) { return hybridclr::startup::GetHooks().Metadata_TryGetNextDheLogicalProperty_0(klass, iter, property); }
size_t hybridclr::metadata::MetadataModule::GetDheLogicalPropertyCount(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheLogicalPropertyCount_0(klass); }
const PropertyInfo* hybridclr::metadata::MetadataModule::GetDheCustomAttributeProperty(Il2CppClass* klass, uint32_t index) { return hybridclr::startup::GetHooks().Metadata_GetDheCustomAttributeProperty_0(klass, index); }
const MethodInfo* hybridclr::metadata::MetadataModule::ResolveDheMethod(const MethodInfo* method) { return hybridclr::startup::GetHooks().Metadata_ResolveDheMethod_0(method); }
bool hybridclr::metadata::MetadataModule::HasDheLogicalEventView(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_HasDheLogicalEventView_0(klass); }
const EventInfo* hybridclr::metadata::MetadataModule::GetFirstDheLogicalEvent(Il2CppClass* klass, void** iter) { return hybridclr::startup::GetHooks().Metadata_GetFirstDheLogicalEvent_0(klass, iter); }
bool hybridclr::metadata::MetadataModule::TryGetNextDheLogicalEvent(Il2CppClass* klass, void** iter, const EventInfo** eventInfo) { return hybridclr::startup::GetHooks().Metadata_TryGetNextDheLogicalEvent_0(klass, iter, eventInfo); }
size_t hybridclr::metadata::MetadataModule::GetDheLogicalEventCount(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Metadata_GetDheLogicalEventCount_0(klass); }
bool hybridclr::metadata::MetadataModule::TryGetDheCustomAttributeSource(const Il2CppImage* image, uint32_t token, const Il2CppImage*& sourceImage, uint32_t& sourceToken) { return hybridclr::startup::GetHooks().Metadata_TryGetDheCustomAttributeSource_0(image, token, sourceImage, sourceToken); }
Il2CppClass* hybridclr::dhe::ResolveReferenceAllocationClass(Il2CppClass* klass) { return hybridclr::startup::GetHooks().Runtime_ResolveReferenceAllocationClass_0(klass); }
const void* hybridclr::dhe::GetPublicationIdentity() { return hybridclr::startup::GetHooks().Runtime_GetPublicationIdentity_0(); }
const Il2CppImage* hybridclr::dhe::ResolvePublicAssemblyImage(const Il2CppImage* image) { return hybridclr::startup::GetHooks().Runtime_ResolvePublicAssemblyImage_0(image); }
Il2CppClass* hybridclr::dhe::SelectReferenceInterfaceIterationClass(Il2CppClass* requested, Il2CppClass* selected, const void* iterator) { return hybridclr::startup::GetHooks().Runtime_SelectReferenceInterfaceIterationClass_0(requested, selected, iterator); }
bool hybridclr::dhe::IsDheAssembly(const Il2CppAssembly* assembly) { return hybridclr::startup::GetHooks().Runtime_IsDheAssembly_0(assembly); }
bool hybridclr::dhe::IsMutableDheAssembly(const Il2CppAssembly* assembly) { return hybridclr::startup::GetHooks().Runtime_IsMutableDheAssembly_0(assembly); }
bool hybridclr::dhe::IsDheModuleInitializationReady(const char* assemblyName) { return hybridclr::startup::GetHooks().Runtime_IsDheModuleInitializationReady_0(assemblyName); }
bool hybridclr::dhe::IsFrozenAotExecutionSource(const Il2CppAssembly* assembly) { return hybridclr::startup::GetHooks().Runtime_IsFrozenAotExecutionSource_0(assembly); }
bool hybridclr::dhe::TryGetVirtualInvokeData(const Il2CppClass* klass, uint16_t logicalSlot, const VirtualInvokeData*& result) { return hybridclr::startup::GetHooks().Runtime_TryGetVirtualInvokeData_0(klass, logicalSlot, result); }
bool hybridclr::dhe::TryGetVirtualInvokeData(const Il2CppClass* klass, const MethodInfo* method, const VirtualInvokeData*& result) { return hybridclr::startup::GetHooks().Runtime_TryGetVirtualInvokeData_1(klass, method, result); }
bool hybridclr::dhe::TryGetVirtualBaseMethod(const MethodInfo* method, bool definition, const MethodInfo*& result) { return hybridclr::startup::GetHooks().Runtime_TryGetVirtualBaseMethod_0(method, definition, result); }
bool hybridclr::dhe::TryGetVirtualReflectionIdentity(const Il2CppClass* reflectedType, const MethodInfo* method, const MethodInfo*& result) { return hybridclr::startup::GetHooks().Runtime_TryGetVirtualReflectionIdentity_0(reflectedType, method, result); }
bool hybridclr::dhe::TryGetInterfaceInvokeData(const Il2CppClass* klass, const Il2CppClass* interfaceType, uint16_t logicalSlot, const VirtualInvokeData*& result) { return hybridclr::startup::GetHooks().Runtime_TryGetInterfaceInvokeData_0(klass, interfaceType, logicalSlot, result); }
bool hybridclr::dhe::IsChangedMethod(const MethodInfo* method) { return hybridclr::startup::GetHooks().Runtime_IsChangedMethod_0(method); }
bool hybridclr::dhe::IsRemovedMethod(const MethodInfo* method) { return hybridclr::startup::GetHooks().Runtime_IsRemovedMethod_0(method); }
bool hybridclr::dhe::IsRemovedType(const Il2CppClass* klass) { return hybridclr::startup::GetHooks().Runtime_IsRemovedType_0(klass); }
bool hybridclr::dhe::ShouldDispatchToInterpreter(const MethodInfo* method) { return hybridclr::startup::GetHooks().Runtime_ShouldDispatchToInterpreter_0(method); }
bool hybridclr::dhe::CanEnterWithBaseAbi(const MethodInfo* method) { return hybridclr::startup::GetHooks().Runtime_CanEnterWithBaseAbi_0(method); }
const MethodInfo* hybridclr::dhe::ResolveAotGuardMethodByToken(const char* assemblyName, uint32_t token) { return hybridclr::startup::GetHooks().Runtime_ResolveAotGuardMethodByToken_0(assemblyName, token); }
const MethodInfo* hybridclr::dhe::ResolveMethodByToken(const char* assemblyName, uint32_t token) { return hybridclr::startup::GetHooks().Runtime_ResolveMethodByToken_0(assemblyName, token); }
const MethodInfo* hybridclr::dhe::ResolveMethodByNameAndToken(const char* assemblyName, const char* declaringType, const char* methodName, uint32_t parameterCount, uint32_t token) { return hybridclr::startup::GetHooks().Runtime_ResolveMethodByNameAndToken_0(assemblyName, declaringType, methodName, parameterCount, token); }
const MethodInfo* hybridclr::dhe::ResolveInterpreterMethod(const MethodInfo* baseMethod) { return hybridclr::startup::GetHooks().Runtime_ResolveInterpreterMethod_0(baseMethod); }
const MethodInfo* hybridclr::dhe::ResolveCurrentExecutionMethod(const MethodInfo* method) { return hybridclr::startup::GetHooks().Runtime_ResolveCurrentExecutionMethod_0(method); }
const MethodInfo* hybridclr::dhe::ResolveNativeReferenceInvokeMethod(const MethodInfo* method, void* receiver) { return hybridclr::startup::GetHooks().Runtime_ResolveNativeReferenceInvokeMethod_0(method, receiver); }
const MethodInfo* hybridclr::dhe::ResolveCurrentReceiverMethod(const MethodInfo* method, void* receiver) { return hybridclr::startup::GetHooks().Runtime_ResolveCurrentReceiverMethod_0(method, receiver); }
const MethodInfo* hybridclr::dhe::ResolveInterpreterVirtualMethod(const MethodInfo* method, void* receiver, const MethodInfo* callSignature) { return hybridclr::startup::GetHooks().Runtime_ResolveInterpreterVirtualMethod_0(method, receiver, callSignature); }
#endif
